// THE WORLD ALIAS TABLE: what people call a city, keyed by the airport row that
// answers to it.
//
// FOUR KINDS OF NAME, and nothing else. Historical names (Peking, Saigon,
// Leningrad). Endonyms in Latin script (München, Wien, Krung Thep, Kaapstad).
// Nicknames that are actually typed (Vegas, Philly, Joburg, Sampa, Baires).
// And the native-script spelling -- Devanagari, Arabic, Cyrillic, CJK, Hangul,
// Thai and the rest -- for the biggest cities, plus the Hindi spelling of the
// places this app's users fly to most. Typos are NOT here: a misspelling is the
// resolver's fuzzy tier's job, and the test file proves that tier catches them
// without help.
//
// EVERY ALIAS MUST RESOLVE TO ITS OWN ROW, EXACTLY, WITH NO RIVAL. That is a
// test, not a hope: tools/test_airports.mjs runs every entry through the
// resolver. An alias that lands on another airport, or ties with one, fails the
// build. "Victoria" is the reason the rule exists.
//
// ROW ALIASES go into the airport row's search string. METRO ALIASES are keys
// of CITY_AIRPORTS, because a name for a metro has to offer the metro's group,
// not one airport of it; each entry below is keyed by an existing curated key.
//
// Applied by tools/add_aliases.mjs, which rewrites lib/airports.ts in place and
// is idempotent. Edit here, run there.

export const ALIASES = {
  europe: {
    MUC: ['münchen', 'muenchen', 'monaco di baviera', 'múnich', 'мюнхен', 'ミュンヘン', '慕尼黑', '뮌헨'],
    VIE: ['wien', 'vienne', 'viena', 'вена', 'ウィーン', '维也纳', '빈'],
    PRG: ['praha', 'prag', 'praga', 'прага', 'プラハ', '布拉格', '프라하'],
    WAW: ['warszawa', 'warschau', 'varsovia', 'varsóvia', 'варшава', 'ワルシャワ', '华沙', '바르샤바'],
    KRK: ['cracow', 'cracovia', 'krakau', 'краков'],
    GDN: ['danzig'],
    WRO: ['breslau'],
    LED: ['saint petersburg', 'sankt peterburg', 'leningrad', 'piter', 'санкт-петербург', 'петербург', 'питер'],
    KZN: ['казань'],
    OVB: ['новосибирск'],
    SVX: ['ekaterinburg', 'sverdlovsk', 'екатеринбург'],
    AER: ['сочи', 'adler'],
    KRR: ['краснодар'],
    VVO: ['владивосток'],
    MSQ: ['минск'],
    RIX: ['рига'],
    TLL: ['tallin', 'таллин', 'reval'],
    VNO: ['wilno', 'vilna', 'вильнюс'],
    ATH: ['athens', 'athina', 'atenas', 'atene', 'αθήνα', 'афины', 'アテネ', '雅典', '아테네'],
    SKG: ['thessaloniki', 'saloniki', 'salonica', 'salonique', 'θεσσαλονίκη', 'салоники'],
    LCA: ['larnaka', 'λάρνακα'],
    LIS: ['lisboa', 'lissabon', 'lisbonne', 'лиссабон', 'リスボン', '里斯本', '리스본'],
    OPO: ['oporto', 'порту'],
    GVA: ['genève', 'genf', 'ginevra', 'ginebra', 'женева', 'ジュネーブ', '日内瓦', '제네바'],
    ZRH: ['zurigo', 'zúrich', 'цюрих', 'チューリッヒ', '苏黎世', '취리히'],
    BSL: ['basle', 'bâle', 'basilea', 'euroairport'],
    BRU: ['bruxelles', 'brussel', 'brüssel', 'bruselas', 'брюссель', 'ブリュッセル', '布鲁塞尔', '브뤼셀'],
    AMS: ['amsterdã', 'ámsterdam', 'амстердам', 'アムステルダム', '阿姆斯特丹', '암스테르담'],
    CPH: ['københavn', 'kopenhagen', 'copenhague', 'copenaghen', 'копенгаген', 'コペンハーゲン', '哥本哈根', '코펜하겐'],
    HEL: ['helsingfors', 'хельсинки', 'ヘルシンキ', '赫尔辛基', '헬싱키'],
    GOT: ['gothenburg', 'gotemburgo'],
    BGO: ['бэрген'],
    KEF: ['reykjavík', 'reykjavik', 'рейкьявик'],
    DUB: ['baile átha cliath', 'dublín', 'дублин', 'ダブリン', '都柏林', '더블린'],
    EDI: ['edimburgo', 'édimbourg', 'эдинбург', 'エディンバラ'],
    MAN: ['mánchester', 'манчестер', 'マンチェスター', '曼彻斯特'],
    NCL: ['newcastle upon tyne'],
    BCN: ['barna', 'barcelone', 'barcellona', 'барселона', 'バルセロナ', '巴塞罗那', '바르셀로나', 'برشلونة'],
    MAD: ['madri', 'мадрид', 'マドリード', '马德里', '마드리드', 'مدريد'],
    SVQ: ['seville', 'sevilla', 'siviglia', 'севилья'],
    BIO: ['bilbo'],
    PMI: ['palma', 'mallorca', 'majorca', 'palma de mallorca', 'пальма'],
    LPA: ['gran canaria'],
    VCE: ['venice', 'venedig', 'venecia', 'венеция', 'ベネチア', 'ヴェネツィア', '威尼斯', '베네치아'],
    FLR: ['florence', 'florenz', 'florencia', 'флоренция', 'フィレンツェ', '佛罗伦萨', '피렌체'],
    NAP: ['naples', 'neapel', 'nápoles', 'неаполь', 'ナポリ', '那不勒斯', '나폴리'],
    TRN: ['turin', 'turín', 'турин', 'トリノ', '都灵', '토리노'],
    BLQ: ['bolonia', 'bologne'],
    PSA: ['pisa'],
    CTA: ['catania'],
    PMO: ['palermo'],
    BER: ['berlín', 'berlim', 'берлин', 'ベルリン', '柏林', '베를린', 'برلين'],
    FRA: ['francfort', 'francoforte', 'fráncfort', 'франкфурт', 'フランクフルト', '法兰克福', '프랑크푸르트'],
    HAM: ['hamburgo', 'hambourg', 'гамбург', 'ハンブルク', '汉堡', '함부르크'],
    DUS: ['duesseldorf', 'дюссельдорф', 'デュッセルドルフ', '杜塞尔多夫'],
    CGN: ['colonia', 'keulen', 'кёльн', 'ケルン', '科隆', '쾰른'],
    STR: ['stoccarda', 'штутгарт', 'シュトゥットガルト', '斯图加特'],
    NUE: ['nürnberg', 'nuernberg', 'nuremberga', 'нюрнберг'],
    HAJ: ['hannover', 'hanover'],
    LEJ: ['лейпциг'],
    BUD: ['budapeste', 'будапешт', 'ブダペスト', '布达佩斯', '부다페스트'],
    BEG: ['belgrade', 'beograd', 'belgrado', 'белград'],
    SOF: ['sofiya', 'sofía', 'софия'],
    ZAG: ['agram', 'загреб'],
    SPU: ['spalato'],
    DBV: ['ragusa'],
    LJU: ['laibach', 'любляна'],
    BTS: ['pressburg', 'pozsony', 'братислава'],
    SJJ: ['сарајево'],
    SKP: ['скопје', 'üsküp'],
    TIA: ['tiranë', 'tirane'],
    MLA: ['valletta', 'luqa'],
    LUX: ['luxemburgo', 'lussemburgo', 'luxemburg'],
    NCE: ['nizza', 'niza', 'ницца'],
    LYS: ['lione', 'лион'],
    MRS: ['marsella', 'marsiglia', 'марсель'],
    ESB: ['анкара', 'أنقرة', 'アンカラ'],
    ADB: ['izmir', 'smyrna', 'измир'],
    AYT: ['анталия', 'анталья'],
    TBS: ['tiflis', 'тбилиси', 'თბილისი'],
    EVN: ['erevan', 'ереван', 'Երևան'],
    GYD: ['bakı', 'баку'],
  },
  'north america': {
    LAS: ['лас-вегас', 'ラスベガス', '拉斯维加斯', '라스베이거스'],
    PHL: ['philly', 'филадельфия', 'フィラデルフィア', '费城'],
    BOS: ['бостон', 'ボストン', '波士顿', '보스턴'],
    MIA: ['майами', 'マイアミ', '迈阿密', '마이애미'],
    ATL: ['атланта', 'アトランタ', '亚特兰大'],
    DFW: ['даллас', 'ダラス', '达拉斯'],
    DEN: ['денвер', 'デンバー', '丹佛'],
    SEA: ['сиэтл', 'シアトル', '西雅图', '시애틀'],
    MCO: ['орландо', 'オーランド', '奥兰多'],
    HNL: ['гонолулу', 'ホノルル', '檀香山'],
    YYZ: ['торонто', 'トロント', '多伦多', '토론토', 'टोरंटो', 'تورونتو'],
    YUL: ['монреаль', 'モントリオール', '蒙特利尔'],
    YVR: ['ванкувер', 'バンクーバー', '温哥华', '밴쿠버'],
    YYC: ['калгари'],
    YOW: ['оттава'],
    CUN: ['канкун', 'カンクン', '坎昆'],
  },
  'latin america': {
    BSB: ['бразилиа'],
    CNF: ['beagá', 'confins'],
    SSA: ['salvador da bahia'],
    FLN: ['floripa'],
    SCL: ['santiago de chile', 'santiago do chile', 'сантьяго', 'サンティアゴ', '圣地亚哥'],
    LIM: ['лима', 'リマ', '利马'],
    BOG: ['богота', 'ボゴタ', '波哥大'],
    MDE: ['rionegro'],
    LPB: ['el alto'],
    VVI: ['santa cruz de la sierra'],
    MVD: ['монтевидео'],
    CCS: ['maiquetía'],
    PTY: ['panama city', 'ciudad de panamá', 'панама'],
    // Not "panama" alone: Panama City, Florida shares the word.
    SJO: ['san josé de costa rica'],
    HAV: ['la habana', 'habana', 'гавана', 'ハバナ', '哈瓦那'],
    SDQ: ['санто-доминго'],
    GUA: ['guatemala city', 'ciudad de guatemala', 'la aurora'],
    BRC: ['bariloche'],
    CUZ: ['cuzco'],
    MBJ: ['mobay'],
    CUR: ['curaçao', 'willemstad'],
    SXM: ['st maarten', 'sint maarten', 'saint martin'],
  },
  'middle east': {
    AUH: ['abudhabi', 'أبو ظبي', 'абу-даби', 'अबू धाबी', 'アブダビ', '阿布扎比', '아부다비'],
    SHJ: ['الشارقة'],
    RUH: ['ar-riyadh', 'ar riyad', 'الرياض', 'эр-рияд', 'रियाद', 'リヤド', '利雅得'],
    JED: ['jidda', 'jiddah', 'djeddah', 'جدة', 'джидда', 'जेद्दा', 'ジッダ', '吉达'],
    DMM: ['الدمام'],
    MED: ['medina', 'madinah', 'al madinah', 'المدينة المنورة'],
    KWI: ['الكويت', 'кувейт', 'कुवैत', 'クウェート', '科威特'],
    MCT: ['masqat', 'مسقط', 'маскат', 'मस्कट', 'マスカット', '马斯喀特'],
    BAH: ['manama', 'المنامة', 'البحرين', 'бахрейн', 'बहरीन'],
    BEY: ['bayrut', 'beyrouth', 'بيروت', 'бейрут', 'ベイルート', '贝鲁特'],
    DAM: ['dimashq', 'damas', 'دمشق', 'дамаск'],
    BGW: ['bagdad', 'بغداد', 'багдад'],
    EBL: ['arbil', 'hawler', 'أربيل'],
    BSR: ['basrah', 'البصرة'],
    TLV: ['tel-aviv', 'tel aviv-yafo', 'ben gurion', 'תל אביב', 'тель-авив', 'تل أبيب', 'テルアビブ', '特拉维夫'],
    MHD: ['mashad', 'مشهد'],
    SYZ: ['شیراز'],
    IFN: ['esfahan', 'اصفهان'],
    TBZ: ['تبریز'],
    SAH: ['sanaa', 'صنعاء'],
    ADE: ['عدن'],
  },
  'south asia': {
    KHI: ['کراچی', 'карачи', 'कराची'],
    LHE: ['لاہور', 'लाहौर'],
    ISB: ['اسلام آباد', 'इस्लामाबाद'],
    PEW: ['پشاور'],
    MUX: ['ملتان'],
    DAC: ['dacca', 'ঢাকা', 'ढाका', 'дакка'],
    CGP: ['chattogram', 'চট্টগ্রাম'],
    KTM: ['katmandu', 'काठमाडौँ', 'काठमांडू', 'катманду'],
    MLE: ['maldives', 'मालदीव'],
    PBH: ['thimphu'],
    KBL: ['kabol', 'کابل', 'कабул'],
    DEL: ['दिल्ली', 'नई दिल्ली', 'デリー', '新德里', '델리', 'دلهي'],
    BOM: ['मुंबई', 'बंबई', 'ムンバイ', '孟买', '뭄바이', 'مومباي'],
    BLR: ['बेंगलुरु', 'बैंगलोर', 'ಬೆಂಗಳೂರು', '班加罗尔'],
    MAA: ['चेन्नई', 'சென்னை', '钦奈'],
    CCU: ['कोलकाता', 'কলকাতা', '加尔各答'],
    HYD: ['हैदराबाद', 'హైదరాబాద్', '海得拉巴'],
    AMD: ['अहमदाबाद', 'અમદાવાદ'],
    PNQ: ['पुणे'],
    JAI: ['जयपुर'],
    LKO: ['लखनऊ'],
    IDR: ['इंदौर'],
    COK: ['कोच्चि', 'കൊച്ചി'],
    VNS: ['वाराणसी', 'बनारस'],
    PAT: ['पटना'],
    BHO: ['भोपाल'],
    NAG: ['नागपुर'],
    IXC: ['चंडीगढ़'],
    ATQ: ['अमृतसर', 'ਅੰਮ੍ਰਿਤਸਰ'],
    GAU: ['गुवाहाटी'],
    SXR: ['श्रीनगर'],
    DED: ['देहरादून'],
    IXR: ['रांची'],
    BBI: ['भुवनेश्वर'],
    VTZ: ['विशाखापत्तनम'],
    TRV: ['तिरुवनंतपुरम', 'തിരുവനന്തപുരം'],
    IXE: ['mangalore', 'मंगलुरु'],
    CJB: ['कोयंबटूर', 'கோயம்புத்தூர்'],
    TRZ: ['तिरुचिरापल्ली', 'त्रिची'],
    RPR: ['रायपुर'],
    UDR: ['उदयपुर'],
    JDH: ['जोधपुर'],
    STV: ['सूरत'],
    BDQ: ['वडोदरा'],
    HSR: ['rajkot', 'राजकोट'],
    IXU: ['sambhajinagar', 'chhatrapati sambhajinagar', 'औरंगाबाद'],
    IXJ: ['जम्मू'],
    IXL: ['लेह'],
    IXB: ['siliguri', 'बागडोगरा', 'सिलीगुड़ी'],
    IXA: ['अगरतला'],
    IMF: ['इंफाल'],
    DIB: ['डिब्रूगढ़'],
    IXZ: ['पोर्ट ब्लेयर'],
    IXD: ['allahabad', 'prayagraj', 'प्रयागराज'],
    PNY: ['pondicherry', 'puducherry'],
    VGA: ['bezawada'],
    IXG: ['belgaum', 'belagavi'],
  },
  'east asia': {
    HND: ['haneda', '羽田'],
    NRT: ['narita', '成田'],
    KIX: ['関西'],
    ITM: ['itami', '伊丹'],
    NGO: ['nagoya', '名古屋', 'chubu', 'centrair', '나고야'],
    CTS: ['sapporo', '札幌', 'chitose', '新千歳', '삿포로'],
    FUK: ['福岡', 'hakata', '후쿠오카'],
    OKA: ['okinawa', 'naha', '那覇', '沖縄', '오키나와'],
    HIJ: ['広島'],
    SDJ: ['仙台'],
    KOJ: ['鹿児島'],
    NGS: ['長崎'],
    CAN: ['canton', 'kwangchow', '广州', '廣州', 'гуанчжоу', '광저우'],
    SZX: ['深圳', 'шэньчжэнь', '선전'],
    CTU: ['成都'],
    CKG: ['chungking', '重庆'],
    XIY: ["xi'an", 'xian', 'sian', '西安'],
    HGH: ['杭州'],
    NKG: ['nanking', '南京'],
    WUH: ['武汉'],
    TSN: ['tientsin', '天津'],
    KMG: ['昆明'],
    XMN: ['amoy', '厦门'],
    CSX: ['长沙'],
    TAO: ['tsingtao', '青岛'],
    DLC: ['大连'],
    SHE: ['沈阳'],
    HRB: ['哈尔滨'],
    URC: ['乌鲁木齐'],
    LXA: ['拉萨'],
    SYX: ['三亚'],
    HAK: ['海口'],
    MFM: ['macao', 'aomen', '澳门', '澳門', '마카오'],
    KHH: ['高雄', 'gaoxiong'],
    ICN: ['incheon', '인천', '仁川'],
    GMP: ['gimpo', '김포'],
    PUS: ['pusan', '부산', '釜山'],
    CJU: ['cheju', '제주'],
    TAE: ['대구'],
    UBN: ['ulan bator', 'ulan-bator', 'улаанбаатар', 'улан-батор', '乌兰巴托'],
    FNJ: ['평양'],
  },
  'southeast asia': {
    DMK: ['don muang', 'ดอนเมือง'],
    CNX: ['chiangmai', 'เชียงใหม่'],
    HKT: ['ภูเก็ต', 'пхукет', 'プーケット', '普吉'],
    KBV: ['กระบี่'],
    USM: ['samui', 'koh samui', 'เกาะสมุย'],
    HDY: ['hatyai', 'หาดใหญ่'],
    UTP: ['pattaya', 'u-tapao', 'พัทยา'],
    // Not "george town": Grand Cayman's capital has the name too.
    PEN: ['pulau pinang', '槟城'],
    JHB: ['johor'],
    BKI: ['kota kinabalu', 'jesselton'],
    KCH: ['kuching'],
    LGK: ['langkawi'],
    DPS: ['巴厘岛', 'бали', 'バリ', '발리'],
    SUB: ['surabaja'],
    YIA: ['yogyakarta', 'jogja', 'jogjakarta', 'yogya', 'djokjakarta'],
    UPG: ['makassar', 'ujung pandang'],
    KNO: ['medan', 'kualanamu'],
    LOP: ['lombok'],
    MNL: ['maynila', '马尼拉', 'манила', 'マニラ', '마닐라'],
    CEB: ['mactan'],
    CRK: ['clark'],
    HAN: ['hà nội', 'ha noi', '河内', 'ханой', 'ハノイ', '하노이'],
    SGN: ['hcmc', 'sài gòn', 'tp hcm', '胡志明市', 'хошимин', 'ホーチミン', '호치민'],
    DAD: ['đà nẵng', 'danang'],
    CXR: ['nha trang', 'cam ranh'],
    PQC: ['phu quoc', 'phú quốc'],
    KTI: ['ភ្នំពេញ', 'пномпень', '金边'],
    SAI: ['siem reap', 'angkor', 'សៀមរាប'],
    VTE: ['viangchan', 'ວຽງຈັນ'],
    RGN: ['ရန်ကုန်', '仰光'],
    MDL: ['mandalay'],
    BWN: ['bandar seri begawan', 'brunei'],
  },
  'central asia': {
    ALA: ['alma-ata', 'alma ata', 'алматы', 'алма-ата'],
    NQZ: ['astana', 'nur-sultan', 'nursultan', 'tselinograd', 'астана', 'нур-султан'],
    TAS: ['toshkent', 'ташкент', 'тошкент'],
    SKD: ['samarqand', 'самарканд'],
    BHK: ['buxoro', 'бухара'],
    DYU: ['душанбе'],
    ASB: ['ashkhabad', 'ашхабад'],
  },
  africa: {
    CAI: ['al qahirah', 'al-qahira', 'el cairo', 'le caire', 'kairo', 'القاهرة', 'каир', 'カイロ', '开罗', 'काहिरा', '카이로'],
    HRG: ['al ghardaqah', 'الغردقة', 'хургада'],
    SSH: ['sharm', 'sharm el sheikh', 'شرم الشيخ', 'шарм-эль-шейх'],
    HBE: ['alexandria', 'iskandariya', 'الإسكندرية'],
    LXR: ['الأقصر'],
    // Not "casa": La Romana's airport is Casa de Campo.
    CMN: ['dar el beida', 'الدار البيضاء', 'касабланка'],
    RAK: ['مراكش', 'марракеш'],
    RBA: ['الرباط'],
    FEZ: ['fes', 'فاس'],
    TNG: ['tangier', 'tanger', 'طنجة'],
    ALG: ['alger', 'el djazair', 'الجزائر', 'алжир'],
    ORN: ['وهران'],
    TUN: ['تونس', 'тунис'],
    DJE: ['جربة'],
    KRT: ['al khartum', 'الخرطوم', 'хартум'],
    ADD: ['addis abeba', 'አዲስ አበባ', 'аддис-абеба'],
    NBO: ['найроби', 'ナイロビ', '内罗毕'],
    ZNZ: ['unguja'],
    JRO: ['kilimanjaro', 'arusha', 'moshi'],
    EBB: ['kampala', 'кампала'],
    LOS: ['eko', 'лагос'],
    ACC: ['аккра'],
    DSS: ['dakar', 'blaise diagne', 'دكار'],
    OUA: ['ouaga'],
    NDJ: ['ndjamena'],
    FIH: ['léopoldville', 'leopoldville'],
    CPT: ['kaapstad', 'capetown', 'кейптаун', 'ケープタウン', '开普敦', '케이프타운'],
    DUR: ['ethekwini'],
    HRE: ['salisbury'],
    VFA: ['vic falls'],
    MPM: ['lourenço marques', 'lourenco marques'],
    TNR: ['tana', 'tananarive'],
    // Not "maurice": Grenada's airport is Maurice Bishop.
    MRU: ['mauritius', 'port louis', 'plaisance', 'मॉरीशस'],
    SEZ: ['seychelles', 'mahé'],
    RUN: ['réunion', 'saint-denis', 'st denis'],
    MGQ: ['muqdisho'],
  },
  oceania: {
    SYD: ['сидней', 'シドニー', '悉尼', '시드니'],
    BNE: ['brissie', 'брисбен'],
    PER: ['перт'],
    OOL: ['gold coast', 'coolangatta'],
    AKL: ['tāmaki makaurau', 'окленд', 'オークランド', '奥克兰'],
    WLG: ['te whanganui-a-tara'],
    CHC: ['ōtautahi'],
    NAN: ['fiji'],
    PPT: ['tahiti'],
    NOU: ['nouméa'],
  },
};

// METRO ALIASES: keyed by an EXISTING key of CITY_AIRPORTS. Each becomes a new
// key over the same group, so "londres" offers Heathrow, Gatwick, Stansted and
// Luton exactly as "london" does.
export const METRO_ALIASES = {
  'london': ['londres', 'londra', 'londyn', 'лондон', 'لندن', 'लंदन', 'ロンドン', '伦敦', '런던'],
  'new york': ['nueva york', 'nova york', 'nova iorque', 'нью-йорк', 'ニューヨーク', '纽约', '뉴욕', 'न्यूयॉर्क', 'نيويورك'],
  'paris': ['parís', 'parigi', 'париж', 'باريس', 'पेरिस', 'パリ', '巴黎', '파리'],
  'rome': ['roma', 'rom', 'рим', 'روما', 'ローマ', '罗马', '로마'],
  'milan': ['milano', 'mailand', 'milán', 'милан', 'ミラノ', '米兰', '밀라노'],
  'moscow': ['moskva', 'moskau', 'moscú', 'moscou', 'москва', 'موسكو', 'मास्को', 'モスクワ', '莫斯科', '모스크바'],
  'istanbul': ['constantinople', 'stamboul', 'استانبول', 'стамбул', 'इस्तांबुल', 'イスタンブール', '伊斯坦布尔', '이스탄불'],
  'stockholm': ['estocolmo', 'stoccolma', 'стокгольм'],
  // A group because Băneasa's row carries the city too; as a row alias
  // "bucharest" tied with it.
  'bucharest': ['bucurești', 'bucuresti', 'bukarest', 'bucarest', 'бухарест'],
  'tokyo': ['東京', '东京', 'tokio', 'токио', '도쿄', 'टोक्यो', 'طوكيو'],
  'osaka': ['大阪', 'осака', '오사카'],
  'beijing': ['peking', 'pekin', 'pékin', '北京', 'пекин', '베이징', 'बीजिंग', 'بكين'],
  'shanghai': ['上海', 'шанхай', '상하이', 'शंघाई', 'شنغهاي'],
  'seoul': ['서울', 'сеул', '首尔', 'ソウル', 'सियोल', 'سيول'],
  'taipei': ['taibei', '台北', '臺北', 'тайбэй', '타이베이'],
  'hong kong': ['hk', 'hongkong', 'xianggang', '香港', 'гонконг', '홍콩', 'हांगकांग', 'هونغ كونغ'],
  'bangkok': ['krung thep', 'krungthep', 'กรุงเทพ', 'กรุงเทพมหานคร', 'бангкок', 'バンコク', '曼谷', '방콕', 'बैंकॉक', 'بانكوك'],
  'singapore': ['sg', 'singapura', '新加坡', 'シンガポール', '싱가포르', 'сингапур', 'सिंगापुर', 'சிங்கப்பூர்', 'سنغافورة'],
  'kuala lumpur': ['kl', '吉隆坡', 'куала-лумпур', 'クアラルンプール', 'कुआलालंपुर', '쿠알라룸푸르'],
  'jakarta': ['jkt', 'djakarta', 'batavia', '雅加达', 'джакарта', 'ジャカルタ', '자카르타'],
  'colombo': ['කොළඹ', 'கொழும்பு', 'कोलंबो', 'коломбо'],
  'goa': ['गोवा'],
  'tehran': ['teheran', 'تهران', 'тегеран', 'テヘラン', '德黑兰'],
  'doha': ['الدوحة', 'доха', 'दोहा', 'ドーハ', '多哈'],
  'dubai': ['dubayy', 'dubaï', 'دبي', 'дубай', 'दुबई', 'ドバイ', '迪拜', '두바이'],
  'amman': ['عمان', 'амман', 'अम्मान'],
  'los angeles': ['la', 'los ángeles', 'лос-анджелес', 'ロサンゼルス', '洛杉矶', '로스앤젤레스', 'لوس أنجلوس'],
  'san francisco': ['sf', 'frisco', 'san fran', 'сан-франциско', 'サンフランシスコ', '旧金山', '三藩市', '샌프란시스코'],
  'washington': ['dc', 'вашингтон', 'ワシントン', '华盛顿', '워싱턴'],
  'chicago': ['чикаго', 'シカゴ', '芝加哥', '시카고'],
  'houston': ['хьюстон', 'ヒューストン', '休斯顿'],
  'mexico city': ['cdmx', 'ciudad de méxico', 'méxico df', 'mexico df', 'мехико', 'メキシコシティ', '墨西哥城', '멕시코시티'],
  'sao paulo': ['sampa', 'san pablo', 'сан-паулу', 'サンパウロ', '圣保罗', '상파울루'],
  'rio de janeiro': ['río de janeiro', 'рио-де-жанейро', 'リオデジャネイロ', '里约热内卢'],
  'buenos aires': ['bsas', 'baires', 'capital federal', 'буэнос-айрес', 'ブエノスアイレス', '布宜诺斯艾利斯', '부에노스아이레스'],
  'johannesburg': ['joburg', 'jozi', "jo'burg", 'egoli', 'йоханнесбург', 'ヨハネスブルグ', '约翰内斯堡'],
  'melbourne': ['мельбурн', 'メルボルン', '墨尔本', '멜버른'],
  'tenerife': ['teneriffa'],
};
