"""Writes lib/zoneAbbr.ts: the letter abbreviation for every zone in the
airport dataset, from the same tz database the server labels its clocks with.

    python tools/gen_zone_abbr.py

WHY A TABLE AND NOT Intl. The server writes "CEST", "IST" and "PDT" because
Python's zoneinfo says so. The phone's Intl gives a different answer per
locale -- en-US says "GMT+2" for Amsterdam, en-GB says "GMT+5:30" for India,
en-IN gets both right and Los Angeles wrong -- so a clock labelled on the
device would disagree with the card's clock for the same airport. This table
is the server's answer, captured.

KEYED BY UTC OFFSET IN MINUTES, because that is what decides between a zone's
two names: the device computes the offset at the instant being shown and looks
it up. Two sample instants, mid-January and mid-July, catch both halves of a
daylight-saving zone in either hemisphere. A zone whose tz database name is
numeric ("+04") is left out; the device then writes "GMT+4", which is exactly
what the server writes for it.
"""
import io
import json
import os
import re
from datetime import datetime, timezone
from zoneinfo import ZoneInfo

HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.dirname(HERE)
src = io.open(os.path.join(APP, "lib", "airports.ts"), encoding="utf8").read()
zones = sorted(set(re.findall(r'^\s*\["[A-Z0-9]{3}", "(?:[^"\\]|\\.)*", "(?:[^"\\]|\\.)*", "(?:[^"\\]|\\.)*", "([^"]+)"', src, re.M)))

samples = [datetime(2026, 1, 15, 12, tzinfo=timezone.utc), datetime(2026, 7, 15, 12, tzinfo=timezone.utc)]
table = {}
for z in zones:
    names = {}
    for t in samples:
        local = t.astimezone(ZoneInfo(z))
        name = local.tzname()
        off = int(local.utcoffset().total_seconds() // 60)
        if name and name[0].isalpha():
            names[str(off)] = name
    if names:
        table[z] = names

lines = [
    "// GENERATED by tools/gen_zone_abbr.py from the tz database the server uses.",
    "// Do not edit by hand: change the airport dataset and run the tool.",
    "//",
    "// Zone -> { UTC offset in minutes -> abbreviation }. A zone or an offset",
    "// that is missing here has no letter name in the tz database, and the",
    "// caller writes \"GMT+4\" for it, as the server does. See zoneAbbrAt.",
    "export const ZONE_ABBR: Record<string, Record<string, string>> = {",
]
for z, names in table.items():
    lines.append(f"  {json.dumps(z)}: {json.dumps(names)},")
lines.append("};")
out = os.path.join(APP, "lib", "zoneAbbr.ts")
io.open(out, "w", encoding="utf8", newline="\n").write("\n".join(lines) + "\n")
print(f"{len(zones)} zones in the dataset, {len(table)} with a letter name; wrote {out}")
